#!/bin/bash
set -e
set -u
set -x

SCRIPT=/opt/omero/web/config/10-signup.omero
cat > $SCRIPT <<EOF
config append omero.web.apps '"omero_signup"'
config set omero.web.signup.admin.user root
config set omero.web.signup.admin.password omero
config set omero.web.signup.group.name NewGroup
EOF

su - omero-web -c "env OMERODIR=$OMERODIR /opt/omero/web/venv3/bin/omero load $SCRIPT"

# Call super. Activates virtualenv
. /infra/app-config
